### ISSUE TITLE
Connection refused errors sometimes

### ISSUE THREAD

**Issue by eugenekainara** [stefansundin/terraform-provider-ssh#9]
Hello!

I'm using your plugin and expect to see "connection refused" or "unexpected EOF" sometimes. It means that it can be 5 successful executions and then 1 or two failed, or it can fails for 5 times and than 1 have passed.

It also reproduced for both local and CI server.
How should I debug following behaviour to provide you with needed info?
I'm using terraform 0.11.14 & provider ssh 0.0.3(but it also related to 0.0.2)
I'm using ssh provider to get my EKS-cluster through bastion instance. 

Log from CI - [ci-log.txt](https://github.com/stefansundin/terraform-provider-ssh/files/3275953/ci-log.txt)

**Comment by stefansundin** [comment]
Hello!

Thanks for the log file, it is very useful to understand what is happening.

Perhaps we shouldn't panic when connections are having problems.. perhaps it makes more sense to just log and ignore it..

Do you want me to help you try out different builds? If you are able to compile it yourself, then I would try commenting out the `panic()` calls here:
https://github.com/stefansundin/terraform-provider-ssh/blob/a7fb598299d24e4480deeab5672b71df5d2cd84c/data_source_ssh_tunnel.go#L189-L203

If you want me to compile for you, please let me know what OS you are running.

If that makes everything more stable, then I will make a new release where I just log warnings instead of panic.

Thanks for the report!

**Comment by eugenekainara** [comment]
Oh, thanks! I'm able to compile binary for both Linux and Mac OS to check is proposed solution is helpful and stable.

**Comment by eugenekainara** [comment]
Seems that proposed solution helps. I've run 5 time locally and on CI server - and no errors occurred. 
I've think we should wait few days so check for stability of solution. I'll come back on next week with updates. 

Thanks a lot!

**Comment by stefansundin** [comment]
Perfect! Glad to hear it seems promising.

**Comment by stefansundin** [comment]
I added this commit: https://github.com/stefansundin/terraform-provider-ssh/commit/9dfc266d71cab53796dc4f87159ea1f2152a9fbd

It would be great if you could pull my code and make sure it works well. Thanks!

**Comment by eugenekainara** [comment]
I've built today new binary and use it on my CI server few times - it also works w/o any issues as for now.

**Comment by eugenekainara** [comment]
It fails one time at CI server with following - [terraform-provider-ssh.log](https://github.com/stefansundin/terraform-provider-ssh/files/3310504/terraform-provider-ssh.log)

**Comment by stefansundin** [comment]
Interesting.. doesn't seem like the same problem though..

In any case, I just released v0.0.4.
